/**
 * prerender.mjs
 * Build-time meta-tag injector for Vite SPA.
 *
 * For each public route it:
 *  1. Reads dist/index.html (the Vite-generated SPA shell)
 *  2. Strips all existing title/meta tags that bots rely on
 *  3. Injects route-specific: title, description, keywords, canonical,
 *     og:* and twitter:* tags, plus og:image per page
 *  4. Writes to dist/{route-path}/index.html
 *
 * This gives WhatsApp/Telegram/Facebook bots and Yandex head-only crawls
 * the correct per-page preview data without requiring a headless browser.
 *
 * og:image strategy:
 *  - Homepage / /doctors  → /og-image.png  (clinic OG banner)
 *  - /services/{id}       → /og/{id}.jpg   (service hero, generated by prepare-og-images.mjs)
 *
 * Runs automatically after `npm run build` via "postbuild" in package.json.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { resolve } from 'path';
import { fileURLToPath } from 'url';

const rootDir = resolve(fileURLToPath(import.meta.url), '..', '..');

// ---------------------------------------------------------------------------
// Site URL
// ---------------------------------------------------------------------------
function resolveSiteUrl() {
  // Read .env.local first, then .env
  for (const envFile of ['.env.local', '.env']) {
    const path = resolve(rootDir, envFile);
    if (existsSync(path)) {
      const content = readFileSync(path, 'utf-8');
      const match = content.match(/^VITE_SITE_URL\s*=\s*(.+)$/m);
      if (match) return match[1].trim().replace(/\/$/, '');
    }
  }
  return process.env.VITE_SITE_URL?.replace(/\/$/, '') ?? 'https://implantium.kz';
}

const SITE = resolveSiteUrl();

// ---------------------------------------------------------------------------
// Route SEO data (mirrors src/data/seo.ts — keep in sync when titles change)
// ---------------------------------------------------------------------------
const ROUTES = [
  {
    path: '/',
    title: 'Имплантация зубов в Актау | Стоматология IMPLANTIUM',
    description:
      'Зубная клиника IMPLANTIUM — стоматология в Актау: имплантация зубов, брекеты, лечение зубов, удаление, чистка и коронки. Запись на консультацию.',
    keywords:
      'стоматология Актау, зубная клиника Актау, имплантация зубов Актау, брекеты Актау, лечение зубов Актау, Ақтау стоматология, тіс емдеу Ақтау',
    ogImage: `${SITE}/og-image.png`,
  },
  {
    path: '/doctors',
    title: 'Стоматологи в Актау | Врачи IMPLANTIUM',
    description:
      'Врачи стоматологической клиники IMPLANTIUM в Актау: имплантолог, ортодонт, терапевт, хирург и специалисты по протезированию.',
    keywords:
      'стоматолог Актау, врач стоматолог Актау, ортодонт Актау, имплантолог Актау, детальный план лечения зубов Актау, Ақтауда стоматолог',
    ogImage: `${SITE}/og-image.png`,
  },
  {
    path: '/services/implants',
    title: 'Имплантация зубов в Актау | IMPLANTIUM',
    description:
      'Имплантация зубов в Актау в клинике IMPLANTIUM: подбор импланта, 3D-диагностика, коронки на имплантах и понятный план лечения.',
    keywords: 'имплантация зубов Актау, импланты Актау, имплантолог Актау, зубной имплант Актау, Ақтауда тіс имплантациясы',
    ogImage: `${SITE}/og/implants.jpg`,
  },
  {
    path: '/services/bone-augmentation',
    title: 'Костная пластика в Актау | IMPLANTIUM',
    description:
      'Костная пластика в Актау перед имплантацией: диагностика, подбор материала и подготовка надежной основы для импланта.',
    keywords: 'костная пластика Актау, наращивание костной ткани Актау, подготовка к имплантации Актау, сүйек пластикасы Ақтау',
    ogImage: `${SITE}/og/bone-augmentation.jpg`,
  },
  {
    path: '/services/frenectomy',
    title: 'Пластика уздечки в Актау | IMPLANTIUM',
    description:
      'Пластика уздечки в Актау: аккуратная стоматологическая процедура под анестезией с понятными рекомендациями по восстановлению.',
    keywords: 'пластика уздечки Актау, подрезание уздечки Актау, френэктомия Актау, жүгеншені кесу Ақтау',
    ogImage: `${SITE}/og/frenectomy.jpg`,
  },
  {
    path: '/services/tooth-extraction',
    title: 'Удаление зуба в Актау | IMPLANTIUM',
    description:
      'Удаление зуба в Актау под анестезией: бережная хирургия, диагностика перед процедурой и рекомендации для спокойного восстановления.',
    keywords: 'удаление зуба Актау, удалить зуб Актау, хирург стоматолог Актау, тіс жұлу Ақтау',
    ogImage: `${SITE}/og/tooth-extraction.jpg`,
  },
  {
    path: '/services/wisdom-tooth-removal',
    title: 'Удаление зуба мудрости в Актау | IMPLANTIUM',
    description:
      'Удаление зуба мудрости в Актау: оценка положения зуба, анестезия, бережное удаление и рекомендации после процедуры.',
    keywords: 'удаление зуба мудрости Актау, зуб мудрости Актау, сложное удаление зуба Актау, ақыл тісін жұлу Ақтау',
    ogImage: `${SITE}/og/wisdom-tooth-removal.jpg`,
  },
  {
    path: '/services/crowns',
    title: 'Коронки на зубы в Актау | IMPLANTIUM',
    description:
      'Коронки на зубы в Актау: металлокерамика, циркон, коронки на импланты и восстановление эстетики улыбки.',
    keywords: 'коронки Актау, коронки на зубы Актау, цирконовые коронки Актау, металлокерамика Актау, тіс қаптамасы Ақтау',
    ogImage: `${SITE}/og/crowns.jpg`,
  },
  {
    path: '/services/dentures',
    title: 'Протезирование зубов в Актау | IMPLANTIUM',
    description:
      'Протезирование зубов в Актау: съемные и несъемные решения, восстановление жевания, дикции и уверенной улыбки.',
    keywords: 'протезирование зубов Актау, протезы Актау, съемные протезы Актау, несъемные протезы Актау, тіс протездері Ақтау',
    ogImage: `${SITE}/og/dentures.jpg`,
  },
  {
    path: '/services/braces',
    title: 'Брекеты в Актау | IMPLANTIUM',
    description:
      'Брекеты в Актау: консультация ортодонта, металлические и самолигирующие системы, план коррекции прикуса и зубного ряда.',
    keywords: 'брекеты Актау, ортодонт Актау, исправление прикуса Актау, металлические брекеты Актау, Ақтауда брекет',
    ogImage: `${SITE}/og/braces.jpg`,
  },
  {
    path: '/services/treatment',
    title: 'Лечение зубов в Актау | IMPLANTIUM',
    description:
      'Лечение зубов в Актау: кариес, пульпит, периодонтит, диагностика и восстановление зуба с комфортной анестезией.',
    keywords: 'лечение зубов Актау, кариес Актау, пульпит Актау, пломба Актау, стоматолог терапевт Актау, Ақтауда тіс емдеу',
    ogImage: `${SITE}/og/treatment.jpg`,
  },
  {
    path: '/services/cleaning',
    title: 'Чистка зубов в Актау | IMPLANTIUM',
    description:
      'Профессиональная чистка зубов в Актау: снятие налета и зубного камня, Air Flow, полировка и профилактика здоровья десен.',
    keywords: 'чистка зубов Актау, профессиональная гигиена Актау, Air Flow Актау, зубной камень Актау, Ақтауда тіс тазалау',
    ogImage: `${SITE}/og/cleaning.jpg`,
  },
];

// ---------------------------------------------------------------------------
// HTML generation helpers
// ---------------------------------------------------------------------------

/** Escape characters that would break HTML attribute values */
function escHtml(str) {
  return str
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

const CLINIC_SERVICES = [
  "Имплантация зубов", "Костная пластика", "Пластика уздечки", "Удаление зуба", 
  "Удаление зуба мудрости", "Коронки", "Протезирование", "Брекеты", "Лечение зубов", "Чистка зубов"
];

function getClinicJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "Dentist",
    "@id": `${SITE}/#clinic`,
    name: "IMPLANTIUM",
    alternateName: ["Стоматологическая клиника IMPLANTIUM", "IMPLANTIUM стоматологиясы"],
    description: "Зубная клиника в Актау: имплантация зубов, брекеты, лечение зубов. Ақтау стоматология — тіс емдеу және тіс имплантациясы.",
    url: SITE,
    telephone: "+77027133939",
    priceRange: "₸₸",
    image: `${SITE}/favicon-512.png`,
    address: {
      "@type": "PostalAddress",
      streetAddress: "13 микрорайон, дом 39",
      addressLocality: "Актау",
      addressRegion: "Мангистауская область",
      postalCode: "130000",
      addressCountry: "KZ",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: 43.667073,
      longitude: 51.136723,
    },
    areaServed: {
      "@type": "City",
      name: "Актау",
    },
    openingHoursSpecification: [
      {
        "@type": "OpeningHoursSpecification",
        dayOfWeek: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
        opens: "10:00",
        closes: "22:00",
      },
      {
        "@type": "OpeningHoursSpecification",
        dayOfWeek: "Sunday",
        opens: "10:00",
        closes: "14:00",
      },
    ],
    medicalSpecialty: ["Dentistry", "Orthodontics", "Dental implantology"],
    availableService: CLINIC_SERVICES.map(name => ({ "@type": "MedicalProcedure", name })),
    sameAs: ["https://www.instagram.com/implantium_aktau/", "https://go.2gis.com/83pdr2"],
  };
}

function getServiceJsonLd(path, title, description) {
  const serviceName = title.split(" | ")[0];
  return {
    "@context": "https://schema.org",
    "@type": "Service",
    "@id": `${SITE}${path}#service`,
    name: serviceName,
    description: description,
    serviceType: serviceName,
    areaServed: {
      "@type": "City",
      name: "Актау",
    },
    provider: {
      "@id": `${SITE}/#clinic`,
    },
    url: `${SITE}${path}`,
  };
}

/** Build a fresh <head> block of SEO tags for a route */
function buildSeoBlock({ title, description, keywords, ogImage, canonical, path }) {
  const jsonLdItems = [getClinicJsonLd()];
  if (path.startsWith('/services/')) {
    jsonLdItems.push(getServiceJsonLd(path, title, description));
  }

  return [
    `<title>${escHtml(title)}</title>`,
    `<meta name="description" content="${escHtml(description)}" />`,
    `<meta name="keywords" content="${escHtml(keywords)}" />`,
    `<link rel="canonical" href="${canonical}" />`,
    `<meta property="og:site_name" content="IMPLANTIUM" />`,
    `<meta property="og:type" content="website" />`,
    `<meta property="og:title" content="${escHtml(title)}" />`,
    `<meta property="og:description" content="${escHtml(description)}" />`,
    `<meta property="og:url" content="${canonical}" />`,
    `<meta property="og:locale" content="ru_KZ" />`,
    `<meta property="og:image" content="${ogImage}" />`,
    `<meta name="twitter:card" content="summary_large_image" />`,
    `<meta name="twitter:title" content="${escHtml(title)}" />`,
    `<meta name="twitter:description" content="${escHtml(description)}" />`,
    `<meta name="twitter:image" content="${ogImage}" />`,
    `<script type="application/ld+json">${JSON.stringify(jsonLdItems)}</script>`
  ].join('\n    ');
}

function injectMeta(template, route, appHtml) {
  const canonical = `${SITE}${route.path === '/' ? '' : route.path}`;

  // Strip all existing title, description, keywords, canonical, og:*, twitter:* tags.
  // The regex handles both single-line and multiline attribute tag formats.
  let html = template
    // <title>...</title>
    .replace(/<title>[^<]*<\/title>/g, '')
    // <meta name="description|keywords|robots|twitter:*" ... />  (single or multiline)
    .replace(/<meta\s+name="(description|keywords|twitter:[^"]*)"[\s\S]*?\/>/g, '')
    // <meta property="og:*" ... />  (single or multiline)
    .replace(/<meta\s+property="og:[^"]*"[\s\S]*?\/>/g, '')
    // <link rel="canonical" ... />
    .replace(/<link\s+rel="canonical"[\s\S]*?\/>/g, '')
    // Collapse runs of blank lines left by removals
    .replace(/\n(\s*\n){2,}/g, '\n\n');

  const seoBlock = buildSeoBlock({ ...route, canonical });

  // Insert SEO block right before </head>
  html = html.replace('</head>', `    ${seoBlock}\n  </head>`);
  
  // Inject SSR HTML into the root div
  if (appHtml) {
    html = html.replace('<div id="root"></div>', `<div id="root">${appHtml}</div>`);
  }

  return html;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

const distDir = resolve(rootDir, 'dist');
const templatePath = resolve(distDir, 'index.html');

if (!existsSync(templatePath)) {
  console.error('[prerender] ❌ dist/index.html not found. Run `npm run build` first.');
  process.exit(1);
}

const template = readFileSync(templatePath, 'utf-8');

let render;
try {
  const serverEntryPath = resolve(rootDir, 'dist-server', 'entry-server.js');
  if (existsSync(serverEntryPath)) {
    const serverEntryUrl = new URL(`file://${serverEntryPath}`).href;
    const entry = await import(serverEntryUrl);
    render = entry.render;
  } else {
    console.warn('[prerender] ⚠️ dist-server/entry-server.js not found. Skipping HTML body prerender.');
  }
} catch (e) {
  console.warn('[prerender] ⚠️ Could not load SSR entry-server.js. Pre-rendering without HTML body.', e.message);
}

for (const route of ROUTES) {
  let appHtml = '';
  if (render) {
    try {
      appHtml = render(route.path);
    } catch (e) {
      console.warn(`[prerender] ⚠️ SSR render failed for ${route.path}:`, e.message);
    }
  }

  const html = injectMeta(template, route, appHtml);

  if (route.path === '/') {
    // Overwrite root index.html in-place
    writeFileSync(templatePath, html, 'utf-8');
    console.log(`[prerender] ✓ /  →  dist/index.html`);
  } else {
    // Write to dist/{path}/index.html
    const routeDir = resolve(distDir, route.path.slice(1));
    mkdirSync(routeDir, { recursive: true });
    const outPath = resolve(routeDir, 'index.html');
    writeFileSync(outPath, html, 'utf-8');
    console.log(`[prerender] ✓ ${route.path}  →  dist${route.path}/index.html`);
  }
}

console.log(`[prerender] ✅ ${ROUTES.length} routes prerendered.`);
