/**
 * prerender.mjs
 * Build-time meta-tag injector for Vite SPA.
 *
 * For each public route it:
 *  1. Reads dist/index.html (the Vite-generated SPA shell)
 *  2. Strips all existing title/meta tags that bots rely on
 *  3. Injects route-specific: title, description, keywords, canonical,
 *     og:* and twitter:* tags, plus og:image per page
 *  4. Writes to dist/{route-path}/index.html
 *
 * This gives WhatsApp/Telegram/Facebook bots and Yandex head-only crawls
 * the correct per-page preview data without requiring a headless browser.
 *
 * og:image strategy:
 *  - Homepage / /doctors  → /og-image.png  (clinic OG banner)
 *  - /services/{id}       → /og/{id}.jpg   (service hero, generated by prepare-og-images.mjs)
 *
 * Runs automatically after `npm run build` via "postbuild" in package.json.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { resolve } from 'path';
import { fileURLToPath } from 'url';
import { PRODUCTION_ORIGIN, SEO_ROUTES } from '../src/seo/registry.ts';

const rootDir = resolve(fileURLToPath(import.meta.url), '..', '..');

const SITE = PRODUCTION_ORIGIN;
const ROUTES = SEO_ROUTES.map((route) => ({
  path: route.localePaths.ru,
  title: route.seo.title.ru,
  description: route.seo.description.ru,
  keywords: route.seo.keywords.join(', '),
  ogImage: `${SITE}${route.ogImagePath}`,
}));

// ---------------------------------------------------------------------------
// HTML generation helpers
// ---------------------------------------------------------------------------

/** Escape characters that would break HTML attribute values */
function escHtml(str) {
  return str
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

const CLINIC_SERVICES = [
  "Имплантация зубов", "Костная пластика", "Пластика уздечки", "Удаление зуба", 
  "Удаление зуба мудрости", "Коронки", "Протезирование", "Брекеты", "Лечение зубов", "Чистка зубов"
];

function getClinicJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "Dentist",
    "@id": `${SITE}/#clinic`,
    name: "IMPLANTIUM",
    alternateName: ["Стоматологическая клиника IMPLANTIUM", "IMPLANTIUM стоматологиясы"],
    description: "Зубная клиника в Актау: имплантация зубов, брекеты, лечение зубов. Ақтау стоматология — тіс емдеу және тіс имплантациясы.",
    url: SITE,
    telephone: "+77027133939",
    priceRange: "₸₸",
    image: `${SITE}/favicon-512.png`,
    address: {
      "@type": "PostalAddress",
      streetAddress: "13 микрорайон, дом 39",
      addressLocality: "Актау",
      addressRegion: "Мангистауская область",
      postalCode: "130000",
      addressCountry: "KZ",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: 43.667073,
      longitude: 51.136723,
    },
    areaServed: {
      "@type": "City",
      name: "Актау",
    },
    openingHoursSpecification: [
      {
        "@type": "OpeningHoursSpecification",
        dayOfWeek: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
        opens: "10:00",
        closes: "22:00",
      },
      {
        "@type": "OpeningHoursSpecification",
        dayOfWeek: "Sunday",
        opens: "10:00",
        closes: "14:00",
      },
    ],
    medicalSpecialty: ["Dentistry", "Orthodontics", "Dental implantology"],
    availableService: CLINIC_SERVICES.map(name => ({ "@type": "MedicalProcedure", name })),
    sameAs: ["https://www.instagram.com/implantium_aktau/", "https://go.2gis.com/83pdr2"],
  };
}

function getServiceJsonLd(path, title, description) {
  const serviceName = title.split(" | ")[0];
  return {
    "@context": "https://schema.org",
    "@type": "Service",
    "@id": `${SITE}${path}#service`,
    name: serviceName,
    description: description,
    serviceType: serviceName,
    areaServed: {
      "@type": "City",
      name: "Актау",
    },
    provider: {
      "@id": `${SITE}/#clinic`,
    },
    url: `${SITE}${path}`,
  };
}

/** Build a fresh <head> block of SEO tags for a route */
function buildSeoBlock({ title, description, keywords, ogImage, canonical, path, noindex = false, includeCanonical = true, includeJsonLd = true }) {
  const jsonLdItems = includeJsonLd ? [getClinicJsonLd()] : [];
  if (includeJsonLd && path.startsWith('/services/')) {
    jsonLdItems.push(getServiceJsonLd(path, title, description));
  }

  const tags = [
    `<title>${escHtml(title)}</title>`,
    `<meta name="description" content="${escHtml(description)}" />`,
    `<meta name="keywords" content="${escHtml(keywords)}" />`,
    `<meta name="robots" content="${noindex ? 'noindex, follow' : 'index, follow'}" />`,
    `<meta property="og:site_name" content="IMPLANTIUM" />`,
    `<meta property="og:type" content="website" />`,
    `<meta property="og:title" content="${escHtml(title)}" />`,
    `<meta property="og:description" content="${escHtml(description)}" />`,
    `<meta property="og:url" content="${canonical}" />`,
    `<meta property="og:locale" content="ru_KZ" />`,
    `<meta property="og:image" content="${ogImage}" />`,
    `<meta name="twitter:card" content="summary_large_image" />`,
    `<meta name="twitter:title" content="${escHtml(title)}" />`,
    `<meta name="twitter:description" content="${escHtml(description)}" />`,
    `<meta name="twitter:image" content="${ogImage}" />`,
  ];

  if (includeCanonical) {
    tags.splice(4, 0, `<link rel="canonical" href="${canonical}" />`);
  }
  if (jsonLdItems.length > 0) {
    tags.push(`<script id="seo-json-ld" type="application/ld+json">${JSON.stringify(jsonLdItems)}</script>`);
  }

  return tags.join('\n    ');
}

function injectMeta(template, route, appHtml) {
  const canonical = `${SITE}${route.path === '/' ? '' : route.path}`;

  // Strip all existing title, description, keywords, canonical, og:*, twitter:* tags.
  // The regex handles both single-line and multiline attribute tag formats.
  let html = template
    // <title>...</title>
    .replace(/<title>[^<]*<\/title>/g, '')
    // <meta name="description|keywords|robots|twitter:*" ... />  (single or multiline)
    .replace(/<meta\s+name="(description|keywords|twitter:[^"]*)"[\s\S]*?\/>/g, '')
    // <meta property="og:*" ... />  (single or multiline)
    .replace(/<meta\s+property="og:[^"]*"[\s\S]*?\/>/g, '')
    // <link rel="canonical" ... />
    .replace(/<link\s+rel="canonical"[\s\S]*?\/>/g, '')
    // Collapse runs of blank lines left by removals
    .replace(/\n(\s*\n){2,}/g, '\n\n');

  const seoBlock = buildSeoBlock({ ...route, canonical });

  // Insert SEO block right before </head>
  html = html.replace('</head>', `    ${seoBlock}\n  </head>`);
  
  // Inject SSR HTML into the root div
  if (appHtml) {
    html = html.replace('<div id="root"></div>', `<div id="root">${appHtml}</div>`);
  }

  return html;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

const distDir = resolve(rootDir, 'dist');
const templatePath = resolve(distDir, 'index.html');

if (!existsSync(templatePath)) {
  console.error('[prerender] ❌ dist/index.html not found. Run `npm run build` first.');
  process.exit(1);
}

const template = readFileSync(templatePath, 'utf-8');

let render;
try {
  const serverEntryPath = resolve(rootDir, 'dist-server', 'entry-server.js');
  if (existsSync(serverEntryPath)) {
    const serverEntryUrl = new URL(`file://${serverEntryPath}`).href;
    const entry = await import(serverEntryUrl);
    render = entry.render;
  } else {
    console.warn('[prerender] ⚠️ dist-server/entry-server.js not found. Skipping HTML body prerender.');
  }
} catch (e) {
  console.warn('[prerender] ⚠️ Could not load SSR entry-server.js. Pre-rendering without HTML body.', e.message);
}

for (const route of ROUTES) {
  let appHtml = '';
  if (render) {
    try {
      appHtml = render(route.path);
    } catch (e) {
      console.warn(`[prerender] ⚠️ SSR render failed for ${route.path}:`, e.message);
    }
  }

  const html = injectMeta(template, route, appHtml);

  if (route.path === '/') {
    // Overwrite root index.html in-place
    writeFileSync(templatePath, html, 'utf-8');
    console.log(`[prerender] ✓ /  →  dist/index.html`);
  } else {
    // Write to dist/{path}/index.html
    const routeDir = resolve(distDir, route.path.slice(1));
    mkdirSync(routeDir, { recursive: true });
    const outPath = resolve(routeDir, 'index.html');
    writeFileSync(outPath, html, 'utf-8');
    console.log(`[prerender] ✓ ${route.path}  →  dist${route.path}/index.html`);
  }
}

const notFoundRoute = {
  path: '/404',
  title: 'Страница не найдена | IMPLANTIUM',
  description: 'Страница не найдена на сайте стоматологической клиники IMPLANTIUM в Актау.',
  keywords: '',
  ogImage: `${SITE}/og-image.png`,
  noindex: true,
  includeCanonical: false,
  includeJsonLd: false,
};
const notFoundHtml = injectMeta(template, notFoundRoute, render ? render('/404') : '');
writeFileSync(resolve(distDir, '404.html'), notFoundHtml, 'utf-8');
console.log('[prerender] ✓ 404 → dist/404.html');

console.log(`[prerender] ✅ ${ROUTES.length} routes prerendered.`);
